job_build_dotnet:
       stage: build
       image: microsoft/dotnet:latest
       script:
         - dotnet restore SimpleBlogEngine
         - dotnet publish SimpleBlogEngine/SimpleBlogEngine.Web -c Release
       artifacts:
         expire_in: 12 hrs
         paths:
          - SimpleBlogEngine/SimpleBlogEngine.Web/bin/Release/netcoreapp2.0/publish/
       

deploy_development:
       stage: deploy
       script:
        - echo "Deploy to Development"
       environment:
         name: Development
         url: https://development.SimpleBlogEngine.com
       only:
        - master