job_build_dotnet:
       stage: build
       image: microsoft/dotnet:latest
       script:
         - dotnet restore SimpleBlogEngine
         - dotnet build SimpleBlogEngine/SimpleBlogEngine -c Release
       artifacts:
         expire_in: 12 hrs
         paths:
          - SimpleBlogEngine/SimpleBlogEngine/bin/Release/netcoreapp2.0/publish/
       environment:
         name: Development
         url: https://development.SimpleBlogEngine.com