job_build_dotnet:
       stage: build
       image: microsoft/dotnet:2.1.200
       script:
         - dotnet restore SimpleBlogEngine
         - dotnet publish SimpleBlogEngine/SimpleBlogEngine -c Release
       artifacts:
         expire_in: 12 hrs
         paths:
          - SimpleBlogEngine/SimpleBlogEngine/bin/Release/netcoreapp1.1/publish/