# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'dotnetcore:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- script: |
    npm install --save-dev webpack
    npm install --save-dev webpack-dev-server
    npm install --save-dev webpack-dev-middleware webpack-hot-middleware
    npm install --save-dev extract-text-webpack-plugin@next
    npm install --save-dev optimize-css-assets-webpack-plugin
  displayName: Install webpack
- script: |
    cd SimpleBlogEngine/SimpleBlogEngine.Web
    npm install
  displayName: Run webpack for SimpleBlogEngine.Web project
- script: |
    dotnet build SimpleBlogEngine/SimpleBlogEngine.sln --configuration $(buildConfiguration)
    dotnet publish SimpleBlogEngine/SimpleBlogEngine.Web/SimpleBlogEngine.Web.csproj --configuration $(buildConfiguration) --output out
  displayName: Publish project
- script: |
# docker build -f Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
# docker login -u $(dockerId) -p $pswd $(dockerid).azurecr.io
# docker push $(dockerId).azurecr.io/$(imageName)
  env:
    pswd: $(dockerPassword)
  displayName: Build and push docker image to ACR 
    